### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by berkaey** [marcomontalbano/figma-export#79] opened 2020-11-06 08:54 UTC
I'm getting `UnhandledPromiseRejectionWarning: Error: read ECONNRESET`,

Is there a debug mode so I can understand what's happening here?

my config file:
```js
module.exports = {
  commands: [
    [
      "components",
      {
        fileId: "XXXX",
        onlyFromPages: ["icons", "illustrations"],
        transformers: [
          require("@figma-export/transform-svg-with-svgo")({
            plugins: [{ removeViewBox: false }, { removeDimensions: true }],
          }),
        ],
        outputters: [
          async (pages) => {
            const output = "./public";
            fs.mkdirSync(output, { recursive: true });
            console.log("OUTPUT", output);
            try {
              pages.forEach(({ name: pageName, components }) => {
                console.log("PAGE", pageName);
                components.forEach(({ name: componentName, svg }) => {
                  const filePath = path.resolve(output, `${componentName}.svg`);

                  let p = filePath.split("/");
                  p.pop();
                  p = p.join("/");

                  fs.mkdirSync(p, { recursive: true });

                  fs.writeFileSync(filePath, svg);

                  console.log("GENERATED", filePath, componentName);
                });
              });
            } catch (e) {
              console.log(e);
            }
          },
        ],
      },
    ],
  ],
};
```

**Comment by berkaey** [comment] 2020-11-06 08:55
BTW: node -v `v12.16.3`

**Comment by berkaey** [comment] 2020-11-06 08:55
full error log ```
(node:38264) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
(node:38264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:38264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by berkaey** [comment] 2020-11-06 09:02
The issue is related to here;
```
transformers: [
          require("@figma-export/transform-svg-with-svgo")({
            plugins: [{ removeViewBox: false }, { removeDimensions: true }],
          }),
        ],
```
when I remove this, it works.

**Comment by berkaey** [comment] 2020-11-06 16:35
It happened again without transformers. Could it be related to rate limiting?

**Comment by marcomontalbano** [comment] 2020-11-07 11:39
Hi @berkaey, thank you for all these details.

I tried by using the same configuration you provided (off-course with a different Figma File) and everything worked properly.
For sure I've to handle all promise rejection and improve the application log to better understand the root cause.

The error `ECONNRESET` should be not related to transformers since they just manipulate strings. `ECONNRESET` is related to a network issue. Figma Export uses the network to connect to Figma Api and to download SVGs. I can also improve the application there to better handle exceptions from Figma.

Rate Limit is for sure another option, I'll investigate more.

Thanks, I'll keep you posted.

**Comment by marcomontalbano** [comment] 2020-11-11 20:22
Hi @berkaey,
I just published the new version [v3.2.0-alpha.0](https://github.com/marcomontalbano/figma-export/releases/tag/v3.2.0-alpha.0) that contains better error handling and limits concurrency when fetching.

If you could test if the issue is still present I'll appreciate it!

```sh
npm install @figma-export/cli@next
```

Thanks!

**Comment by berkaey** [comment] 2020-11-12 16:48
I tried 3 times after and after, looks like it is fixed, thanks!

**Comment by marcomontalbano** [comment] 2020-11-14 18:11
Hi @berkaey,
I'm going to close the issue since I just release the new version [v3.2.0](https://github.com/marcomontalbano/figma-export/releases/tag/v3.2.0).

I was looking at your configuration file and seems to me that you could replace your custom outputter with [@figma-export/output-components-as-svg](https://www.npmjs.com/package/@figma-export/output-components-as-svg).

```js
outputters: [
    require('@figma-export/output-components-as-svg')({
        output: './public',
        getDirname: (options) => options.dirname,
    })
]
```

The option `getDirname` gives you the ability to change the folder structure when exporting components.

**Closed by marcomontalbano** 2020-11-14 18:11 UTC
Labels: Issue: bug

**Comment by berkaey** [comment] 2020-11-16 11:41
> Hi @berkaey,
> I'm going to close the issue since I just release the new version [v3.2.0](https://github.com/marcomontalbano/figma-export/releases/tag/v3.2.0).
> 
> I was looking at your configuration file and seems to me that you could replace your custom outputter with [@figma-export/output-components-as-svg](https://www.npmjs.com/package/@figma-export/output-components-as-svg).
> 
> ```js
> outputters: [
>     require('@figma-export/output-components-as-svg')({
>         output: './public',
>         getDirname: (options) => options.dirname,
>     })
> ]
> ```
> 
> The option `getDirname` gives you the ability to change the folder structure when exporting components.

yes I noticed that too, but I also replace some IDs in SVG file so this is why I implemented it like this.
